### ISSUE TITLE
Optional style tip for lots of arguments

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei-orka/myclientele-f5-client#14]
https://github.com/thinkful-ei-orka/myclientele-f5-client/blob/eb3e8110b45fcd6884ebdfe24430f8bba65de402/src/services/client-api-service.js#L14-L22

When you have lots of arguments, sometimes it's better to pass in an object with all the properties you need, rather than a list of 8 arguments that need to be in the exact specific order.

Here are some arguments about this on StackOverflow: https://stackoverflow.com/questions/12826977/multiple-arguments-vs-options-object

**Comment by bookcasey** [comment]
Same deal for `updateClient` as well

**Comment by JZPoteat** [comment]
Moved params into an object and passed the object into the client api service.
