### ISSUE TITLE
Don't parse non-json body response for DELETE etc

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei-orka/myclientele-f5-client#16]
https://github.com/thinkful-ei-orka/myclientele-f5-client/blob/eb3e8110b45fcd6884ebdfe24430f8bba65de402/src/services/reports-api-service.js#L70

We're are parsing the json body here.

`DELETE` returns a 204, no-content

https://github.com/thinkful-ei-orka/myclientele-f5-api/blob/67de63c8ffa7b08effff4993036830e852873932/src/report/report-router.js#L124-L126

This happens in several places throughout the app

**Comment by JZPoteat** [comment]
Should it just return 0 in this case?

**Comment by bookcasey** [comment]
That's seems to be what we're doing in the rest of the app, so following that pattern sounds good

**Comment by JZPoteat** [comment]
Fixed the update and delete functions on the reports api service.  Looking for more places to update in regards to this issue.
