### ISSUE TITLE
Populate context with empty default values

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei-orka/myclientele-f5-client#17]
It's a good practice to populate the context with default empty values

https://github.com/thinkful-ei-orka/myclientele-f5-client/blob/5835f8ffbbe5ad4b877c027e8e1a9aa9b9268dcf/src/contexts/PrivateContext.js#L3

For example:

```
React.createContext({
  name: '',  
  myFunction: () => {},
});
```

Mostly helpful for testing.

**Comment by JZPoteat** [comment]
Added default values for private context
